source 'https://rubygems.org'

gem 'rails'
gem 'sass'
gem 'sqlite3'
gem 'sass-rails'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'grape'
gem 'uglifier'
gem 'zip-zip'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'rubocop'
  gem 'nokogiri'
end

gem 'vitals', path: '../../../'
